#!/usr/bin/env python3
"""
gen_nginx_conf.py - print the nginx location block for the UserAlerts web
panel.

weewx.conf's [UserAlerts][[Web]] section (url_path/host/port/htpasswd_file)
is the single source of truth for where this panel is mounted and where it
listens -- useralerts_web.py reads host/port from the same place. This
script reads it too, so the nginx side is never a hand-maintained copy that
can drift out of sync with what the app is actually bound to or what URL
path it's meant to sit behind.

Usage:
    python3 gen_nginx_conf.py --config /etc/weewx/weewx.conf
    python3 gen_nginx_conf.py --config /etc/weewx/weewx.conf > /tmp/alerts.conf
    # then paste/include the output into the server{} block that already
    # serves your WeeWX public_html (must be the HTTPS one -- basic auth
    # over plain HTTP just leaks the password), and:
    sudo nginx -t && sudo systemctl reload nginx

Re-run this (and reload nginx) any time you change [UserAlerts][[Web]] in
weewx.conf -- don't hand-edit the generated block, edit weewx.conf instead.
"""

import argparse
import sys

import weecfg


def render(url_path, host, port, htpasswd_file):
    url_path = '/' + url_path.strip('/')  # normalize: no trailing slash, exactly one leading slash
    return """\
# Generated by gen_nginx_conf.py from weewx.conf's [UserAlerts][[Web]].
# Edit weewx.conf, not this block, then regenerate.

location = {path} {{
    return 301 {path}/;
}}

location {path}/ {{
    auth_basic           "UserAlerts";
    auth_basic_user_file  {htpasswd};

    # Trailing slash on both this and proxy_pass strips the "{path}" prefix
    # before it reaches Flask; X-Forwarded-Prefix tells the app (via
    # ProxyFix in useralerts_web.py) to put it back when building URLs, so
    # generated links/redirects/forms stay under {path}/.
    proxy_pass http://{host}:{port}/;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix {path};
}}
""".format(path=url_path, host=host, port=port, htpasswd=htpasswd_file)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--config', dest='config_path', metavar='CONFIG_FILE',
                         help='Path to weewx.conf')
    args = parser.parse_args()

    _, config_dict = weecfg.read_config(args.config_path, [])
    web_dict = config_dict.get('UserAlerts', {}).get('Web', {})
    if not web_dict:
        sys.exit("No [UserAlerts][[Web]] section found in weewx.conf -- add one first "
                 "(see the useralerts_web.py module docstring for the fields it reads).")

    sys.stdout.write(render(
        url_path=web_dict.get('url_path', '/alerts'),
        host=web_dict.get('host', '127.0.0.1'),
        port=web_dict.get('port', '8081'),
        htpasswd_file=web_dict.get('htpasswd_file', '/etc/nginx/.htpasswd_alerts'),
    ))


if __name__ == '__main__':
    main()
